# Generated by Django 3.2.3 on 2021-06-08 17:38

from django.db import migrations, models
import sales_manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0002_alter_userratebook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=sales_manager.models.upload_to),
        ),
    ]
