# Generated by Django 3.2.3 on 2021-05-20 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер')),
                ('number_of_people', models.IntegerField(default=1, verbose_name='Вмещает людей')),
                ('room_area', models.FloatField(verbose_name='Площадь')),
                ('is_lux', models.BooleanField(default=False, verbose_name='Люкс')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронировано')),
                ('booked_from', models.DateField(blank=True, null=True)),
                ('booked_to', models.DateField(blank=True, null=True)),
                ('booked_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
