# Generated by Django 3.2.3 on 2021-05-28 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_room_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='equipment_quality',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество оборудования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='food_quality',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Качество еды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='location',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Расположение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='territory_condition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние прилегающей территории'),
            preserve_default=False,
        ),
    ]
