# Generated by Django 3.2.3 on 2021-06-01 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0006_rename_occupation_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Проживание', 'verbose_name_plural': 'Проживание'},
        ),
        migrations.AlterModelOptions(
            name='rentermessage',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
        migrations.RemoveField(
            model_name='rentermessage',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='rentermessage',
            name='room',
        ),
        migrations.AddField(
            model_name='rentermessage',
            name='rent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hotel.rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_to',
            field=models.DateField(verbose_name='Дата отъезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(verbose_name='Дата отъезда'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='renter',
            field=models.ManyToManyField(related_name='rented', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='rentermessage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
