# Generated by Django 3.2.3 on 2021-06-03 10:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0008_auto_20210602_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('avg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='rated_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTypeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_type_service', to='hotel.typeservice')),
                ('user', models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rated_type_service', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type_service')},
            },
        ),
    ]
