# Generated by Django 3.2.3 on 2021-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_typeservice_usertypeservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeservice',
            options={'verbose_name': 'Тип сервиса', 'verbose_name_plural': 'Типы сервиса'},
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='avg_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
