# Generated by Django 3.2.3 on 2021-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20210603_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel/photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
