# Generated by Django 3.2.3 on 2021-06-10 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20210610_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='rent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hotel.rent'),
        ),
    ]
